# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=1, verbose_name='Chinese character')),
                ('mc_i', models.CharField(max_length=1, verbose_name='initial consonant in Middle Chinese')),
                ('mc_f', models.CharField(max_length=1, verbose_name='final in Middle Chinese')),
                ('mc_t', models.CharField(max_length=1, verbose_name='tone in Middle Chinese')),
                ('mc_o', models.CharField(max_length=1, verbose_name='openness in Middle Chinese')),
                ('mc_d', models.CharField(max_length=1, verbose_name='division in Middle Chinese')),
            ],
        ),
        migrations.CreateModel(
            name='Taishanese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_i', models.CharField(default='', max_length=3, verbose_name='initial consonant in Taishanese')),
                ('ts_f', models.CharField(max_length=4, verbose_name='final in Taishanese')),
                ('ts_t', models.CharField(max_length=3, verbose_name='tone in Taishanese')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsmc.Character', verbose_name='Chinese character')),
            ],
        ),
    ]
