# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0004_character_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='note',
            field=models.CharField(blank=True, max_length=10, verbose_name='note on character'),
        ),
    ]
