# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0005_auto_20171126_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='openness',
            field=models.CharField(max_length=1, verbose_name='openness in Middle Chinese (1 = open, 2 = closed)'),
        ),
    ]
