# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0006_auto_20171126_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taishanese',
            name='initial',
            field=models.CharField(blank=True, max_length=3, verbose_name='initial consonant in Taishanese'),
        ),
    ]
