# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0008_auto_20171216_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='char',
            field=models.CharField(max_length=2, verbose_name='Chinese character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='initial',
            field=models.CharField(max_length=1, verbose_name='initial consonant in Middle Chinese'),
        ),
    ]
