# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0009_auto_20171216_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='note',
            field=models.CharField(blank=True, max_length=20, verbose_name='note on character'),
        ),
    ]
