# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0012_character_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='taishanese',
            name='note',
            field=models.CharField(blank=True, max_length=20, verbose_name='note'),
        ),
    ]
