# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0016_auto_20180105_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='note',
            field=models.CharField(blank=True, max_length=50, verbose_name='note on character'),
        ),
    ]
