# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-17 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0018_auto_20180331_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='external',
            field=models.BooleanField(default=False, verbose_name='from outside chengyun + jiyun?'),
        ),
        migrations.AddField(
            model_name='character',
            name='jiyun_only',
            field=models.BooleanField(default=False, verbose_name='jiyun only?'),
        ),
        migrations.AddField(
            model_name='character',
            name='variants',
            field=models.CharField(blank=True, max_length=2, verbose_name='more common character'),
        ),
        migrations.AlterField(
            model_name='taishanese',
            name='source',
            field=models.CharField(max_length=1, verbose_name='source (d = dad, m = mum, u = me but unverified, g = grandma)'),
        ),
    ]
