# Generated by Django 2.1.1 on 2018-09-24 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0022_auto_20180717_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='taishanese',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
    ]
