# Generated by Django 2.1.1 on 2018-09-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0024_auto_20180924_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taishanese',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
    ]
