# Generated by Django 2.1.1 on 2019-03-03 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0025_auto_20180924_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, verbose_name='Name')),
                ('baxter', models.CharField(max_length=8, verbose_name="Baxter's transcription")),
            ],
        ),
        migrations.CreateModel(
            name='Initial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, verbose_name='Name')),
                ('baxter', models.CharField(max_length=4, verbose_name="Baxter's transcription")),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='final_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tsmc.Final'),
        ),
        migrations.AddField(
            model_name='character',
            name='initial_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tsmc.Initial'),
        ),
    ]
