# Generated by Django 2.1.1 on 2019-03-03 05:42

from django.db import migrations

# https://stackoverflow.com/a/36000084

def link_initials(apps, schema_editor):
    Initial = apps.get_model('tsmc', 'Initial')
    Character = apps.get_model('tsmc', 'Character')
    for character in Character.objects.all():
        # https://docs.djangoproject.com/en/2.1/ref/models/querysets/#get-or-create
        # created is a bool specifying whether new obj was created
        initial, created = Initial.objects.get_or_create(name=character.initial)
        character.initial_key = initial
        character.save()

def link_finals(apps, schema_editor):
    Final = apps.get_model('tsmc', 'Final')
    Character = apps.get_model('tsmc', 'Character')
    for character in Character.objects.all():
        final, created = Final.objects.get_or_create(name=character.final)
        character.final_key = final
        character.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0026_auto_20190303_1842'),
    ]

    operations = [
        migrations.RunPython(link_initials),
        migrations.RunPython(link_finals),
    ]
