# Generated by Django 2.1.1 on 2019-03-03 05:42

from django.db import migrations

# https://stackoverflow.com/a/36000084

def link_initials(apps, schema_editor):
    pass

def link_finals(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0026_auto_20190303_1842'),
    ]

    operations = [
    ]
