# Generated by Django 2.1.1 on 2019-03-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0027_transfer_initials_finals'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dot',
            field=models.BooleanField(default=False, verbose_name='has mysterious dot to the left'),
        ),
    ]
