# Generated by Django 2.1.1 on 2019-03-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0028_character_dot'),
    ]

    operations = [
        migrations.AddField(
            model_name='initial',
            name='other',
            field=models.CharField(blank=True, max_length=1, verbose_name='Other initials this encompasses'),
        ),
    ]
