# Generated by Django 3.0.4 on 2020-11-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0031_auto_20190303_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='dot',
        ),
    ]
