# Generated by Django 4.0.5 on 2022-06-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0032_remove_character_dot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='final',
            options={'ordering': ('name', 'baxter')},
        ),
        migrations.AlterModelOptions(
            name='initial',
            options={'ordering': ('name', 'baxter')},
        ),
    ]
