# Generated by Django 4.0.5 on 2022-11-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0033_alter_final_options_alter_initial_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gloss',
            field=models.CharField(blank=True, max_length=50, verbose_name='gloss'),
        ),
    ]
