# Generated by Django 4.0.5 on 2022-11-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsmc', '0034_character_gloss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='final',
        ),
        migrations.RemoveField(
            model_name='character',
            name='initial',
        ),
    ]
