# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0002_auto_20171209_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='char',
            new_name='word',
        ),
        migrations.AddField(
            model_name='word',
            name='gloss',
            field=models.CharField(default='', max_length=25, verbose_name='Gloss'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='pron',
            field=models.CharField(default='blank', max_length=20, verbose_name='Pronunciation'),
            preserve_default=False,
        ),
    ]
