# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0005_auto_20180201_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='note',
            field=models.CharField(blank=True, max_length=50, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pron',
            field=models.CharField(max_length=30, verbose_name='Pronunciation'),
        ),
    ]
