# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0007_auto_20180201_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='note',
            field=models.CharField(blank=True, max_length=150, verbose_name='Note'),
        ),
    ]
