# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0008_auto_20180519_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='gloss',
            field=models.CharField(max_length=100, verbose_name='Gloss'),
        ),
        migrations.AlterField(
            model_name='word',
            name='note',
            field=models.CharField(blank=True, max_length=100, verbose_name='Note'),
        ),
    ]
