# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-17 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0010_auto_20180629_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=60, verbose_name='Sentence')),
                ('romanised', models.CharField(max_length=200, verbose_name='Romanised')),
                ('english', models.CharField(max_length=200, verbose_name='English translation')),
            ],
        ),
    ]
