# Generated by Django 2.1.1 on 2018-09-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0011_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='source',
            field=models.CharField(default='d', max_length=1, verbose_name='source (d = dad, m = mum, u = me, g = grandma)'),
            preserve_default=False,
        ),
    ]
