# Generated by Django 2.1.1 on 2019-02-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0012_sentence_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pron',
            field=models.CharField(max_length=50, verbose_name='Pronunciation'),
        ),
    ]
