# Generated by Django 2.1.1 on 2019-03-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0013_auto_20190207_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='gloss',
            field=models.TextField(verbose_name='Gloss/definition(s)'),
        ),
    ]
