# Generated by Django 2.1.1 on 2019-03-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0015_auto_20190303_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
