# Generated by Django 2.1.1 on 2019-04-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0017_auto_20190418_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
    ]
