# Generated by Django 2.1.1 on 2019-04-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0018_auto_20190418_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pron',
            field=models.CharField(max_length=75, verbose_name='Pronunciation'),
        ),
    ]
