# Generated by Django 2.1.1 on 2019-04-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0019_auto_20190424_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
    ]
