# Generated by Django 2.1.1 on 2019-04-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0020_sentence_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
