# Generated by Django 2.2.1 on 2019-06-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0021_sentence_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
