# Generated by Django 2.2.1 on 2019-06-11 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0022_auto_20190610_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='pron',
            new_name='pron_old',
        ),
        migrations.AlterField(
            model_name='sentence',
            name='source',
            field=models.CharField(max_length=1, verbose_name='source (d = dad, m = mum, u = me, gm = grandma)'),
        ),
        migrations.CreateModel(
            name='Pron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pron', models.CharField(max_length=50, verbose_name='Pronunciation')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('source', models.CharField(max_length=1, verbose_name='Source')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tspron.Word')),
            ],
        ),
    ]
