# Generated by Django 2.2.1 on 2019-06-11 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0025_auto_20190611_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='Date'),
            preserve_default=False,
        ),
    ]
