# Generated by Django 2.2.1 on 2019-06-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0027_auto_20190611_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pron',
            name='source',
            field=models.CharField(max_length=2, verbose_name='Source'),
        ),
    ]
