# Generated by Django 2.2.1 on 2019-06-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0028_auto_20190611_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public?'),
        ),
    ]
