# Generated by Django 2.2.1 on 2019-06-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0029_word_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pron',
            name='source',
            field=models.CharField(max_length=5, verbose_name='Source'),
        ),
    ]
