# Generated by Django 2.2.1 on 2019-06-13 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0032_remove_pron_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_words', to='tspron.Word')),
                ('to_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_words', to='tspron.Word')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='related',
            field=models.ManyToManyField(related_name='_word_related_+', through='tspron.WordRelationship', to='tspron.Word'),
        ),
    ]
