# Generated by Django 2.2.1 on 2019-06-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0033_auto_20190613_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='related',
        ),
        migrations.DeleteModel(
            name='WordRelationship',
        ),
    ]
