# Generated by Django 2.2.1 on 2019-06-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0034_auto_20190613_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='related',
            field=models.ManyToManyField(related_name='_word_related_+', to='tspron.Word'),
        ),
    ]
