# Generated by Django 3.0.2 on 2020-01-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tspron', '0035_word_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='related',
        ),
    ]
